name: Deploy portfolio website to server

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: portfolio
        
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Build Angular app
        working-directory: portfolio
        run: npm run build -- --configuration production

      - name: Verify build output
        run: ls -l portfolio/dist/portfolio

      - name: Move build output
        run: |
          mkdir dist
          cp -r portfolio/dist/portfolio/* dist/

      - name: Clean target directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 2222
          script: |
            rm -rf /opt/docker/traefik-from-scratch/sites/yaneric.porogoramer.com/*

      - name: Deploy via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 2222
          source: "dist/*"
          target: "/opt/docker/traefik-from-scratch/sites/yaneric.porogoramer.com"
          overwrite: true
