name: Deploy portfolio website to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build project
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Deploy via SSH 
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_DEPLOY_HOST }}
          username: ${{ secrets.DEV_DEPLOY_USER }}
          key: ${{ secrets.DEV_DEPLOY_KEY }}
          port: 2222
          source: "dist/portfolio/*"
          target: "/var/www/yaneric.porogoramer.com"