name: Deploy portfolio website to server

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: portfolio
        
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: portfolio

      
      - name: Verify build output
        run: ls -l portfolio/dist/portfolio

      - name: Move build output
        run: |
          mkdir dist
          cp -r portfolio/dist/portfolio/* dist/

      - name: Deploy via SSH 
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 2222
          source: "dist/*"
          target: "/var/www/yaneric.porogoramer.com"
          overwrite: true
